### ISSUE TITLE
Outdated pyfolio crashes the tutorials

### ISSUE THREAD

**Issue by dev590t** [AI4Finance-Foundation/FinRL#579]
## Description
Pyfolio isn't still maintained. Last pyfolio version isn't compatible with last numpy version.

## Reproduce bug
run tutorials/1-Introduction/FinRL_PortfolioAllocation_NeurIPS_2020.ipynb

## Exception
Get exception
```
File /mnt/linuxProgram/workspace/FinRL/__pypackages__/3.8/lib/pyfolio/timeseries.py:1008, in gen_drawdown_table(returns, top)
   1003     df_drawdowns.loc[i, 'Duration'] = len(pd.date_range(peak,
   1004                                                         recovery,
   1005                                                         freq='B'))
   1006 df_drawdowns.loc[i, 'Peak date'] = (peak.to_pydatetime()
   1007                                     .strftime('%Y-%m-%d'))
-> 1008 df_drawdowns.loc[i, 'Valley date'] = (valley.to_pydatetime()
   1009                                       .strftime('%Y-%m-%d'))
   1010 if isinstance(recovery, float):
   1011     df_drawdowns.loc[i, 'Recovery date'] = recovery

AttributeError: 'numpy.int64' object has no attribute 'to_pydatetime'
```
## Version
pyfolio                    0.9.2
numpy                      1.22.3

## Solution possible
Maybe it is better to replace pyfolio by [quantstats](https://github.com/ranaroussi/quantstats). Else we must specify the version of numpy compatible with last pyfolio version in setup.py.

**Comment by randheerDas** [comment]
Got this to work with the numpy 1.22.3 . Had to modify the pyfolio(0.92) : timeseries.py module. Can we contribute back to PyFolio?

**Comment by dev590t** [comment]
@randheerDas I see many PR in pyfolio aren't merged. I don't think that it's worth contributing to pyfolio. The author seems abondon the project. Quantstas has same feature, and is actively maintened, it is more promising.

Here a example of quantstats to replace pyfolio in tutorials:
Pyfolio:
```
with pyfolio.plotting.plotting_context(font_scale=1.1):
        pyfolio.create_full_tear_sheet(returns = DRL_strat,
                                       benchmark_rets=baseline_returns, set_context=False)
```
Quantstas:
```
import quantstats as qs
def f(input):
    index_1 = pd.to_datetime(input.index).tz_localize(None)
    s = pd.Series(data = input.values, index = index_1)    
    return s
qs.reports.full(returns = f(DRL_strat),benchmark=f(baseline_returns))
```

**Comment by flyingsandwich1** [comment]
> Got this to work with the numpy 1.22.3 . Had to modify the pyfolio(0.92) : timeseries.py module. Can we contribute back to PyFolio?

What modifications did you make to pyfolio? Are you able to share?

**Comment by randheerDas** [comment]
> > Got this to work with the numpy 1.22.3 . Had to modify the pyfolio(0.92) : timeseries.py module. Can we contribute back to PyFolio?
> 
> What modifications did you make to pyfolio? Are you able to share?

Will share the details. The change was to upgrade the timeseries.py module in pyfolio.
